#pragma once

//Table constants
#define DEFAULT_NAME "table"
#define DEFAULT_LENGTH 10

//Matrix constants
#define DEFAULT_NUMBER_OF_ROWS 10
#define DEFAULT_NUMBER_OF_COLUMNS 10

//Mscn constants
#define DEFAULT_D_VALUE 10
#define DEFAULT_F_VALUE 10
#define DEFAULT_M_VALUE 10
#define DEFAULT_S_VALUE 10

#define READ "r+"
#define WRITE "w+"

#define MIN_GENERATED_VALUE_IN_CD 0
#define MAX_GENERATED_VALUE_IN_CD 10
#define MIN_GENERATED_VALUE_IN_CF 0
#define MAX_GENERATED_VALUE_IN_CF 10
#define MIN_GENERATED_VALUE_IN_CM 0
#define MAX_GENERATED_VALUE_IN_CM 10
#define MIN_GENERATED_VALUE_IN_UD 0
#define MAX_GENERATED_VALUE_IN_UD 10
#define MIN_GENERATED_VALUE_IN_UF 0
#define MAX_GENERATED_VALUE_IN_UF 10
#define MIN_GENERATED_VALUE_IN_UM 0
#define MAX_GENERATED_VALUE_IN_UM 10
#define MIN_GENERATED_VALUE_IN_SD 0
#define MAX_GENERATED_VALUE_IN_SD 200
#define MIN_GENERATED_VALUE_IN_SF 0
#define MAX_GENERATED_VALUE_IN_SF 200
#define MIN_GENERATED_VALUE_IN_SM 0
#define MAX_GENERATED_VALUE_IN_SM 200
#define MIN_GENERATED_VALUE_IN_SS 0
#define MAX_GENERATED_VALUE_IN_SS 200
#define MIN_GENERATED_VALUE_IN_PS 0
#define MAX_GENERATED_VALUE_IN_PS 100

#define MINXD_DEFAULT_VALUES 0
#define MAXXD_DEFAULT_VALUES 100
#define MINXF_DEFAULT_VALUES 0
#define MAXXF_DEFAULT_VALUES 100
#define MINXM_DEFAULT_VALUES 0
#define MAXXM_DEFAULT_VALUES 100
#define REDUCE_VALUE 1

//Solution Constants
#define MIN_GENERATED_VALEUE_IN_XD 0
#define MAX_GENERATED_VALEUE_IN_XD 100
#define MIN_GENERATED_VALEUE_IN_XF 0
#define MAX_GENERATED_VALEUE_IN_XF 100
#define MIN_GENERATED_VALEUE_IN_XM 0
#define MAX_GENERATED_VALEUE_IN_XM 100

//RandomSearch Constants
#define MIN_GENERATED_VALUE 0
#define MAX_GENERATED_VALUE 100


//DiffEvol Constants
#define CROSSPROB 0.5
#define DIFFWEIGHT 0.8
